# Generated by Django 2.2.5 on 2021-02-17 23:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210217_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('image', models.CharField(default='https://picsum.photos/id/237/200', max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('likes', models.CharField(max_length=350)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
