  
# Generated by Django 3.1.6 on 2021-02-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.CharField(default='https://picsum.photos/id/237/200/300', max_length=350),
        ),
    ]