# Generated by Django 3.1.6 on 2021-02-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=128, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('nick_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=350)),
            ],
        ),
    ]
