# Generated by Django 3.1.6 on 2021-02-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210203_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default=None, max_length=350),
        ),
    ]
