# Generated by Django 3.1.6 on 2021-02-15 19:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128)),
                ('avatar_image', models.CharField(default=None, max_length=350)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]